packages:
  - examples/*
  - packages/*
allowBuilds:
  "@vscode/vsce-sign": false
  esbuild: true
  keytar: false
minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/*"
overrides:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vitest: npm:@voidzero-dev/vite-plus-test@0.2.4
