packages:
  - examples/*
  - packages/*
allowBuilds:
  "@vscode/vsce-sign": set this to true or false
  esbuild: true
  keytar: set this to true or false
minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/*"
overrides:
  vite: npm:@voidzero-dev/vite-plus-core@0.1.24
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.24
